### ISSUE TITLE
When using "Increment within DAG..." option, the Save options at the top of the page do not save the form.

### ISSUE THREAD

**Issue by tlstoffs** [ctsit/record_autonumbering#8]
When using this record numbering option, the Save options at the top of the page do not work. Nothing happens using any of the Save options. You have to scroll to the bottom of the page to Save the form. Once you click on Save at the bottom of the page, the top buttons work again.

![Screen Shot 2021-03-17 at 10 46 38 AM](https://user-images.githubusercontent.com/21062119/111487282-99873900-870e-11eb-9158-d4e77cd21a67.png)

![Screen Shot 2021-03-17 at 10 47 12 AM](https://user-images.githubusercontent.com/21062119/111487317-a1df7400-870e-11eb-842e-1d9e4dcc86cc.png)

![Screen Shot 2021-03-17 at 10 47 23 AM](https://user-images.githubusercontent.com/21062119/111487330-a4da6480-870e-11eb-992f-27d732731fa2.png)

**Comment by michael-bentz** [comment]
@tlstoffs Can you share the project xml you are using to test?

**Comment by ChemiKyle** [comment]
@mbentz-uf I can send it to you, I've got access to that one.

**Comment by tlstoffs** [comment]
See attached.


>^..^<
Taryn L. Stoffs, M.S.
REDCap Team Lead
Clinical & Translational Science Informatics & Technology (CTS-IT)
University of Florida
PO Box 100212
2405 SW Archer Road
Gainesville, Florida 32608


From: mbentz-uf ***@***.***>
Reply-To: ctsit/record_autonumbering ***@***.***>
Date: Thursday, March 18, 2021 at 10:20 AM
To: ctsit/record_autonumbering ***@***.***>
Cc: Taryn Stoffs ***@***.***>, Mention ***@***.***>
Subject: Re: [ctsit/record_autonumbering] When using "Increment within DAG..." option, the Save options at the top of the page do not save the form. (#8)

[External Email]


@tlstoffs<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tlstoffs&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=7BsQz4jlLe3tmfcQuGqM0g&m=rKbj32J2Rqbnia1ci3wO6vOsfYWKVRZ_RtaRevZMHKE&s=MM5Zx6_q04JU19w7apkJ8jee_zQuo94mSFuXfN5QxUU&e=> Can you share the project xml you are using to test?

**Comment by ChemiKyle** [comment]
Interestingly, the top buttons' events appear to have been overridden:

```js
function onclick(event) {
  return false;
}
```
They literally do nothing!

**Comment by michael-bentz** [comment]
Addressed by PR #9
